##### Copyright 2026 Google LLC.

In [3]:
import pandas as pd

df = pd.read_csv("tips.csv")
print(df.head())
print(df.describe())

print(df['sex'].value_counts())
print(df.sex.count())
print(df.total_bill.mean())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000
sex
Male      157
Female     87
Name: count, dtype: int64
244
19.78594262295082

In [5]:
df[['tip']]
print(df[['tip']].head())
print(df[['tip']].mean())

df[['tatal_bill','tip']]
df[df.columns[1:3]]
df.select_dtypes(include='number')

    tip
0  1.01
1  1.66
2  3.50
3  3.31
4  3.61
tip    2.998279
dtype: float64

In [7]:
df.iloc[1:4,:]
df.iloc[1:4,]
df.iloc[1:4]

df.iloc[:, 1:3]
df.iloc[1:4,1:3]

df.loc[1:4,['total_bill']]
df.loc[1:4,['total_bill','tip']]

      tip     sex
0    1.01  Female
1    1.66    Male
2    3.50    Male
3    3.31    Male
4    3.61  Female
..    ...     ...
239  5.92    Male
240  2.00  Female
241  2.00    Male
242  1.75    Male
243  3.00  Female

[244 rows x 2 columns]

In [13]:
df[df.day.isin(['Sun','Sat'])]
df[df.day.isin(['Sun','Sat'])]['tip'].mean()

df[df.day.isin(['Sun','Sat'])].sum()

df[df['size'] > 3]

df[(df['size'] > 3) & (df['total_bill'] > 20.0)]

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
23        39.42  7.58    Male     No   Sat  Dinner     4
33        20.69  2.45  Female     No   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
54        25.56  4.34    Male     No   Sun  Dinner     4
56        38.01  3.00    Male    Yes   Sat  Dinner     4
59        48.27  6.73    Male     No   Sat  Dinner     4
77        27.20  4.00    Male     No  Thur   Lunch     4
85        34.83  5.17  Female     No  Thur   Lunch     4
95        40.17  4.73    Male    Yes   Fri  Dinner     4
116       29.93  5.07    Male     No   Sun  Dinner     4
119       24.08  2.92  Female     No  Thur   Lunch     4
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
153       24.55  2.00    Male     No   Sun  Dinner     4
155       29.85  5.14  Female     No   Sun  Dinner     5
156       48.17  5.00    Male     No   Sun  Dinner     6
157       25.00  3.75  Female     No   Sun  Dinner     4
160       21.50  3.50    Male     No   Sun  Dinner     4
167       31.71  4.50    Male     No   Sun  Dinner     4
180       34.65  3.68    Male    Yes   Sun  Dinner     4
183       23.17  6.50    Male    Yes   Sun  Dinner     4
185       20.69  5.00    Male     No   Sun  Dinner     5
187       30.46  2.00    Male    Yes   Sun  Dinner     5
197       43.11  5.00  Female    Yes  Thur   Lunch     4
204       20.53  4.00    Male    Yes  Thur   Lunch     4
207       38.73  3.00    Male    Yes   Sat  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
212       48.33  9.00    Male     No   Sat  Dinner     4
216       28.15  3.00    Male    Yes   Sat  Dinner     5
219       30.14  3.09  Female    Yes   Sat  Dinner     4
227       20.45  3.00    Male     No   Sat  Dinner     4
230       24.01  2.00    Male    Yes   Sat  Dinner     4

In [14]:
df.sort_values('total_bill',ascending= True)
df.sort_values(['size','tip'],ascending= True)
df.sort_values(['size','tip'],ascending= [True,False])

     total_bill   tip     sex smoker   day    time  size
222        8.58  1.92    Male    Yes   Fri   Lunch     1
82        10.07  1.83  Female     No  Thur   Lunch     1
67         3.07  1.00  Female    Yes   Sat  Dinner     1
111        7.25  1.00  Female     No   Sat  Dinner     1
88        24.71  5.85    Male     No  Thur   Lunch     2
..          ...   ...     ...    ...   ...     ...   ...
187       30.46  2.00    Male    Yes   Sun  Dinner     5
141       34.30  6.70    Male     No  Thur   Lunch     6
143       27.05  5.00  Female     No  Thur   Lunch     6
156       48.17  5.00    Male     No   Sun  Dinner     6
125       29.80  4.20  Female     No  Thur   Lunch     6

[244 rows x 7 columns]